stages:
  - convert
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update && apt-get install -y php ruby-full

convert_to_html:
  stage: convert
  script:
    - echo "Starting PHP to HTML conversion..."
    - cd src
    - if [ -d HTML ]; then rm -rf HTML; fi
    - mkdir -p HTML
    - echo "Converting PHP files to HTML..."
    - find . -type f -name "*.php" -not -path "*include*" -exec sh -c '
        for php_file; do
          echo "Processing $php_file";
          relative_path="${php_file#./}";
          html_file="HTML/${relative_path%.php}.html";
          mkdir -p "$(dirname "$html_file")";
          php "$php_file" > "$html_file";
        done
      ' sh {} +
    - if [ -d assets ]; then cp -rf ./assets ./HTML; fi
    - if [ -f ./_config.yml ]; then cp -f ./_config.yml ./HTML; fi
    - if [ -d ../HTML ]; then rm -rf ../HTML; fi
    - mv -f ./HTML ..
    - echo "PHP to HTML conversion completed."

  artifacts:
    paths:
      - HTML
    expire_in: 1 hour

build_jekyll:
  stage: build
  dependencies:
    - convert_to_html
  script:
    - echo "Installing Jekyll..."
    - gem install bundler jekyll
    - echo "Building the Jekyll site..."
    - jekyll build -s ./HTML -d ./_site

  artifacts:
    paths:
      - _site
    expire_in: 1 hour

pages:
  stage: deploy
  script:
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - latest
