stages:
  - convert
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

convert_to_html:
  stage: convert
  image: docker:latest
  services:
    - docker:rc-dind
  script:
    - echo "Run HTML conversion..."
    - apt-get update && apt-get install -y docker.io
    - docker build -t hofmann-convert-release -f build/convert.Dockerfile .
    - docker run --rm -v "$CI_PROJECT_DIR:/app" hofmann-convert-release sh -c /app/build/.build
    - echo "HTML conversion completed."
  artifacts:
    paths:
      - HTML
    expire_in: 1 hour
  only:
    - latest  

build_jekyll:
  stage: build
  dependencies:
    - convert_to_html
  script:
    - apt-get update && apt-get install -y ruby-full
    - echo "Installing Jekyll..."
    - gem install bundler jekyll
    - echo "Building the Jekyll site..."
    - jekyll build -s ./HTML -d ./_site
  artifacts:
    paths:
      - _site
    expire_in: 1 hour
  only:
    - latest  

pages:
  stage: deploy
  script:
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - latest  
